"""added_constraint_unique_book_title_year

Revision ID: a1bc99da9f52
Revises: af78caf673a7
Create Date: 2026-06-14 19:13:09.320763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1bc99da9f52'
down_revision: Union[str, Sequence[str], None] = 'af78caf673a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_book_title_author_year', ['title', 'author', 'year'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('uix_book_title_author_year', type_='unique')

    # ### end Alembic commands ###
