"""added_created_at_for_book

Revision ID: af78caf673a7
Revises: 539083072f12
Create Date: 2026-06-12 08:34:59.102357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af78caf673a7'
down_revision: Union[str, Sequence[str], None] = '539083072f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_book_genre', ['book_id', 'genre_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint('uix_book_genre', type_='unique')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
