"""fix_book_genre_many_to_many

Revision ID: c45a5bfdad42
Revises: 7055fb1d333d
Create Date: 2026-06-11 13:37:17.572488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45a5bfdad42'
down_revision: Union[str, Sequence[str], None] = '7055fb1d333d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_book_genre_book', 'book', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_book_genre_genre', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('book_selection', schema=None) as batch_op:
        # УДАЛИЛИ drop_constraint, оставили только создание новых именованных ключей
        batch_op.create_foreign_key('fk_book_selection_selection', 'selection', ['selection_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_book_selection_book', 'book', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_selection', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_selection_selection', type_='foreignkey')
        batch_op.drop_constraint('fk_book_selection_book', type_='foreignkey')
        batch_op.create_foreign_key('fk_book_selection_book', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('fk_book_selection_selection', 'selection', ['selection_id'], ['id'])

    with op.batch_alter_table('book_genre', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_genre_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_book_genre_book', type_='foreignkey')

    # ### end Alembic commands ###